### ISSUE TITLE
Integrate Travis CI service

### ISSUE THREAD

**Issue by peter279k** [Rundiz/thai-date#1]
As title, can I add the Travis CI service?
And I can also enhance tests.

If possible, I can help this issue and send the PR.

Thanks.

**Comment by ve3** [comment]
I'm not familiar with that. Sorry, but I think it will be more difficult or more task to do. I'm trying to keep it simple and easy.

**Comment by peter279k** [comment]
Why? I think  the unit test can make this repo reliable and make sure your code do well with the expected behavior.

**Comment by ve3** [comment]
It is already have unit test using phpunit (phpunit.xml and tests folder).
Why? As I said - because I'm not familiar with that.
